package by.htp.les18.bean;

public enum TYPE_OF_FEATURE {
	POWER_CONSUMPTION, WEIGHT, CAPACITY, DEPTH, HEIGHT, WIDTH, BATTERY_CAPACITY, OP_SYSTEM, MEMORY_ROM, SYSTEM_MEMORY,
	CPU, DISPLAY_INCHES, FREEZER_CAPACITY, OVERALL_CAPACITY, FILTER_TYPE, BAG_TYPE, WAND_TYPE, MOTOR_SPEED_REGULATION,
	CLEANING_WIDTH, FLASH_MEMORY_CAPACITY, COLOR, NUMBER_OF_SPEAKERS, FREQENCY_RANGE, CORD_LENGTH, MAX_TEMPERATURE,
	WIRE_LENGTH, MATERIAL, HEAT_TIME, NO_SUCH_TYPE;
}
